---
- name: download rust installer
  get_url:
    url: "https://sh.rustup.rs"
    dest: /usr/local/sbin/rustup-install.sh
    mode: 0755
    owner: root
    group: root
  tags:
    - rust.install

- name: install rust
  command: "/usr/local/sbin/rustup-install.sh -y"
  args:
    chdir: /home/{{ solana_user }}/
  become: true
  become_user: {{ solana_user }}
  register: install_output
  changed_when: false
  tags:
    - rust.install

- name: debug
  debug: var=install_output
  tags:
    - rust.install

- name: install rustfmt
  command: rustup component add rustfmt
  args:
    chdir: /home/{{ solana_user }}/
  environment:
    PATH: /bin:/usr/bin:/usr/local/bin:/home/{{ solana_user }}/.cargo/bin
  become: true
  become_user: {{ solana_user }}
  register: rustup_output
  changed_when: false
  tags:
    - rust.install

- name: debug
  debug: var=rustup_output
  tags:
    - rust.install